# calc_stats.R
# created by: Nathan Wikle, 30 June 2015
# last edited: 30 June 2015

# a function to calculate statistics from a list of dataframes
# input: 1) l: a list of dataframes generated by many_simulations()
# output: a list consisting of:
#   1) average_time: a dataframe with mean time, standard deviation,
# number of times infected, and proprtion_times infected for each state.
#   2) was_infected_by: a list of dataframes, where each df describes 
# the origins of infection for a specific state, and the related percentage.
#   3) has_infected: a list of dataframes, where each df shows which states
# where infected by a particular state, and the related percentage
#   4) transmissions: a dataframe detailing how often each state has 
# infected other states
#
# Note that all helper functions found within calc_stats can be found
# in the file: stats_helper_functions.R
calc_stats <- function(l){
  n<-length(l) # number of simulations
  states<-l[[1]][,1]  # vector of state names
  numStates<-length(states) # number of states
  
  # the following vectors are used in the calculation of average_time
  mean_time <- rep(0,numStates) # mean time until infection
  sd_time <- rep(0,numStates) # standard deviation of time
  times_infected <- rep(0,numStates) # number of times state was infected
  proportion_times <- rep(0,numStates) # percent times infected
  # dataframe for average_time
  avgInf <- data.frame(states,mean_time,sd_time,times_infected,proportion_times)
  
  # used to calculate how state becomes infected
  infected_by <- list(rep(data.frame(),times=numStates))
  # used to calculate how often state infects others
  has_infected <- list(rep(data.frame(),times=numStates))
  #determine which states infect most often
  most_transmissions<-rep(0,numStates)
  trans<-data.frame(state=states,most_transmissions)
  
  for (i in 1:numStates){
    # determine how state i became infected
    infected_by[[i]]<-infected(l,i) 
    # determine which states were infected by i
    has_infected[[i]]<-infects(l,i)
    # count number of transmissions resulting from state i
    trans$most_transmissions[i] <- sum(has_infected[[i]]$times_infected) 
    # the following is used to calculate the average number of times
    # state i was infected.
    
    # vector with times state i was infected
    row<-na.omit(sapply(l,function(x) as.numeric(x[i,3]))) 
    # only run when a state was infected at least once
    if (length(row) != 0) {
      avgInf[i,2]<- mean(row)      # calculate mean
      avgInf[i,3]<- sd(row)        # calculate sd
      avgInf[i,4]<- length(row)    # calculate total # time infected
      avgInf[i,5]<- avgInf[i,4]/n  # calculate percent time infected
    } else { # add NA's, since these values don't exist
      avgInf[i,2]<-NA 
      avgInf[i,3]<-NA
    }
  }
  # order avgerage time by mean_time, increasing
  avgInf<- avgInf[order(avgInf$mean_time),]
  # order transmissions by most_transmissions, decreasing
  trans<- trans[order(trans$most_transmissions,decreasing=TRUE),]
  names(infected_by)<-states   # name each df for a state
  names(has_infected)<-states  # name each df for a state
  
  # create output list
  stats<-list(avgInf,infected_by,has_infected,trans)
  names(stats)<-c("average_time","was_infected_by","has_infected","transmissions")
  stats # output the statistics
}
